# LOAD DATA

In [208]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

In [209]:
df = pd.read_csv('C:/Users/jojo0/OneDrive/Documents/Competition/Gammafest-2026/Datasets/df_train_clean.csv')
display(df.head())
display(df.info())

,Id,match_id,date,gender,team,opponent,is_home,neutral,tournament,venue_country,team_goals,opp_goals,days_since_last_match_team,days_since_last_match_opp,elo_team,elo_opponent,confederation_team,confederation_opp,population_team,population_opp,gdp_per_capita_team,gdp_per_capita_opp,altitude_venue,distance_travel_team,distance_travel_opp,temperature_venue,is_train,first_match_team,first_match_opp,match_key,team_points_last5,team_points_last10,team_gd_last5,team_avg_goals_last5,team_avg_conceded_last5,team_win_rate_last10,h2h_points_last5,h2h_gd_last5,opp_points_last5,opp_points_last10,opp_gd_last5,opp_avg_goals_last5,opp_avg_conceded_last5,opp_win_rate_last10,points_last5_diff,gd_last5_diff
0,M000001_Scotland,M000001,1872-11-30,M,Scotland,England,1,0,Friendly,Scotland,0.0,0.0,0.0,0.0,1500.0,1500.0,UEFA,UEFA,9893316.0,9893316.0,3784.449144,3784.449144,127.0,0.0,0.0,19.352352,1,1,1,1872-11-30||England||Scotland,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0
1,M000001_England,M000001,1872-11-30,M,England,Scotland,0,0,Friendly,Scotland,0.0,0.0,0.0,0.0,1500.0,1500.0,UEFA,UEFA,9893316.0,9893316.0,3784.449144,3784.449144,127.0,0.0,0.0,19.352352,1,1,1,1872-11-30||England||Scotland,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0
2,M000002_England,M000002,1873-03-08,M,England,Scotland,1,0,Friendly,England,4.0,2.0,98.0,98.0,1500.0,1500.0,UEFA,UEFA,9893316.0,9893316.0,3784.449144,3784.449144,127.0,0.0,0.0,19.352352,1,0,0,1873-03-08||England||Scotland,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,M000002_Scotland,M000002,1873-03-08,M,Scotland,England,0,0,Friendly,England,2.0,4.0,98.0,0.0,1484.0,1516.0,UEFA,UEFA,9893316.0,9893316.0,3784.449144,3784.449144,127.0,0.0,0.0,19.352352,1,0,1,1873-03-08||England||Scotland,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,M000003_Scotland,M000003,1874-03-07,M,Scotland,England,1,0,Friendly,Scotland,2.0,1.0,364.0,364.0,1484.0,1516.0,UEFA,UEFA,9893316.0,9893316.0,3784.449144,3784.449144,127.0,0.0,0.0,19.352352,1,0,0,1874-03-07||England||Scotland,1.0,1.0,-2.0,1.0,2.0,0.0,1.0,-2.0,4.0,4.0,2.0,2.0,1.0,0.5,-3.0,-4.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78772 entries, 0 to 78771
Data columns (total 46 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Id                          78772 non-null  object
 1   match_id                    78772 non-null  object
 2   date                        78772 non-null  object
 3   gender                      78772 non-null  object
 4   team                        78772 non-null  object
 5   opponent                    78772 non-null  object
 6   is_home                     78772 non-null  int64
 7   neutral                     78772 non-null  int64
 8   tournament                  78772 non-null  object
 9   venue_country               78772 non-null  object
 10  team_goals                  78772 non-null  float64
 11  opp_goals                   78772 non-null  float64
 12  days_since_last_match_team  78772 non-null  float64
 13  days_since_last_match_opp   78772 non-null  float64
 14  elo_team                    78772 non-null  float64
 15  elo_opponent                78772 non-null  float64
 16  confederation_team          78772 non-null  object
 17  confederation_opp           78772 non-null  object
 18  population_team             78772 non-null  float64
 19  population_opp              78772 non-null  float64
 20  gdp_per_capita_team         78772 non-null  float64
 21  gdp_per_capita_opp          78772 non-null  float64
 22  altitude_venue              78772 non-null  float64
 23  distance_travel_team        78772 non-null  float64
 24  distance_travel_opp         78772 non-null  float64
 25  temperature_venue           78772 non-null  float64
 26  is_train                    78772 non-null  int64
 27  first_match_team            78772 non-null  int64
 28  first_match_opp             78772 non-null  int64
 29  match_key                   78772 non-null  object
 30  team_points_last5           78772 non-null  float64
 31  team_points_last10          78772 non-null  float64
 32  team_gd_last5               78772 non-null  float64
 33  team_avg_goals_last5        78772 non-null  float64
 34  team_avg_conceded_last5     78772 non-null  float64
 35  team_win_rate_last10        78772 non-null  float64
 36  h2h_points_last5            78772 non-null  float64
 37  h2h_gd_last5                78772 non-null  float64
 38  opp_points_last5            78772 non-null  float64
 39  opp_points_last10           78772 non-null  float64
 40  opp_gd_last5                78772 non-null  float64
 41  opp_avg_goals_last5         78772 non-null  float64
 42  opp_avg_conceded_last5      78772 non-null  float64
 43  opp_win_rate_last10         78772 non-null  float64
 44  points_last5_diff           78772 non-null  float64
 45  gd_last5_diff               78772 non-null  float64
dtypes: float64(30), int64(5), object(11)
memory usage: 27.6+ MB

None

In [210]:
date_column = 'date'
categorical_columns = ['gender', 'team', 'opponent', 'tournament', 'venue_country', 'confederation_team', 'confederation_opp']
unnecessary_columns = ['Id', 'match_key', 'is_train']

In [211]:
df[date_column] = pd.to_datetime(df[date_column])
df[categorical_columns] = df[categorical_columns].astype('category')
df = df.drop(columns=unnecessary_columns)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78772 entries, 0 to 78771
Data columns (total 43 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   match_id                    78772 non-null  object
 1   date                        78772 non-null  datetime64[ns]
 2   gender                      78772 non-null  category
 3   team                        78772 non-null  category
 4   opponent                    78772 non-null  category
 5   is_home                     78772 non-null  int64
 6   neutral                     78772 non-null  int64
 7   tournament                  78772 non-null  category
 8   venue_country               78772 non-null  category
 9   team_goals                  78772 non-null  float64
 10  opp_goals                   78772 non-null  float64
 11  days_since_last_match_team  78772 non-null  float64
 12  days_since_last_match_opp   78772 non-null  float64
 13  elo_team                    78772 non-null  float64
 14  elo_opponent                78772 non-null  float64
 15  confederation_team          78772 non-null  category
 16  confederation_opp           78772 non-null  category
 17  population_team             78772 non-null  float64
 18  population_opp              78772 non-null  float64
 19  gdp_per_capita_team         78772 non-null  float64
 20  gdp_per_capita_opp          78772 non-null  float64
 21  altitude_venue              78772 non-null  float64
 22  distance_travel_team        78772 non-null  float64
 23  distance_travel_opp         78772 non-null  float64
 24  temperature_venue           78772 non-null  float64
 25  first_match_team            78772 non-null  int64
 26  first_match_opp             78772 non-null  int64
 27  team_points_last5           78772 non-null  float64
 28  team_points_last10          78772 non-null  float64
 29  team_gd_last5               78772 non-null  float64
 30  team_avg_goals_last5        78772 non-null  float64
 31  team_avg_conceded_last5     78772 non-null  float64
 32  team_win_rate_last10        78772 non-null  float64
 33  h2h_points_last5            78772 non-null  float64
 34  h2h_gd_last5                78772 non-null  float64
 35  opp_points_last5            78772 non-null  float64
 36  opp_points_last10           78772 non-null  float64
 37  opp_gd_last5                78772 non-null  float64
 38  opp_avg_goals_last5         78772 non-null  float64
 39  opp_avg_conceded_last5      78772 non-null  float64
 40  opp_win_rate_last10         78772 non-null  float64
 41  points_last5_diff           78772 non-null  float64
 42  gd_last5_diff               78772 non-null  float64
dtypes: category(7), datetime64[ns](1), float64(30), int64(4), object(1)
memory usage: 22.5+ MB

In [212]:
df.isnull().sum().sum()

np.int64(0)

In [213]:
df = df.sort_values(by=['team', 'opponent', 'date'])

# SPLITTING DATA

In [214]:
unique_matches = df['match_id'].unique()

match_split_index = int(len(unique_matches)*0.8)

train_match_id = unique_matches[:match_split_index]
test_match_id = unique_matches[match_split_index:]

train_df = df[df['match_id'].isin(train_match_id)]
test_df = df[df['match_id'].isin(test_match_id)]

target = ['team_goals', 'opp_goals']

X_train = train_df.drop(columns=target + ['match_id', 'date', 'team', 'opponent'])
y_train = train_df[target]

X_test = test_df.drop(columns=target + ['match_id', 'date', 'team', 'opponent'])
y_test = test_df[target]

display(X_train.shape)
display(X_test.shape)

(63016, 37)

(15756, 37)

In [215]:
display(X_train.columns)

Index(['gender', 'is_home', 'neutral', 'tournament', 'venue_country',
       'days_since_last_match_team', 'days_since_last_match_opp', 'elo_team',
       'elo_opponent', 'confederation_team', 'confederation_opp',
       'population_team', 'population_opp', 'gdp_per_capita_team',
       'gdp_per_capita_opp', 'altitude_venue', 'distance_travel_team',
       'distance_travel_opp', 'temperature_venue', 'first_match_team',
       'first_match_opp', 'team_points_last5', 'team_points_last10',
       'team_gd_last5', 'team_avg_goals_last5', 'team_avg_conceded_last5',
       'team_win_rate_last10', 'h2h_points_last5', 'h2h_gd_last5',
       'opp_points_last5', 'opp_points_last10', 'opp_gd_last5',
       'opp_avg_goals_last5', 'opp_avg_conceded_last5', 'opp_win_rate_last10',
       'points_last5_diff', 'gd_last5_diff'],
      dtype='object')

# PREPROCESSING

In [216]:
for col in categorical_columns:
    print(f'Unique values of {col}: {df[col].nunique()}')

Unique values of gender: 2
Unique values of team: 287
Unique values of opponent: 287
Unique values of tournament: 186
Unique values of venue_country: 268
Unique values of confederation_team: 7
Unique values of confederation_opp: 7

In [217]:
display(X_train.shape)
display(X_test.shape)

(63016, 37)

(15756, 37)

## Encoding

### gender

In [218]:
gender_map = {
    'M': 1,
    'W': 0
}

X_train['gender'] = X_train['gender'].map(gender_map)
X_test['gender'] = X_test['gender'].map(gender_map)

In [219]:
display(X_train.shape)
display(X_test.shape)

(63016, 37)

(15756, 37)

### confederation_*

In [220]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

X_train_ohe = ohe.fit_transform(X_train[['confederation_team', 'confederation_opp']])
X_test_ohe = ohe.transform(X_test[['confederation_team', 'confederation_opp']])


X_train_df = pd.DataFrame(X_train_ohe, columns=ohe.get_feature_names_out(), index=X_train.index)
X_test_df = pd.DataFrame(X_test_ohe, columns=ohe.get_feature_names_out(), index=X_test.index)

In [221]:
X_train = pd.concat([X_train, X_train_df], axis=1)
X_test = pd.concat([X_test, X_test_df], axis=1)

X_train = X_train.drop(columns=['confederation_team', 'confederation_opp'])
X_test = X_test.drop(columns=['confederation_team', 'confederation_opp'])

In [222]:
display(X_train.head())
display(X_test.head())

,gender,is_home,neutral,tournament,venue_country,days_since_last_match_team,days_since_last_match_opp,elo_team,elo_opponent,population_team,population_opp,gdp_per_capita_team,gdp_per_capita_opp,altitude_venue,distance_travel_team,distance_travel_opp,temperature_venue,first_match_team,first_match_opp,team_points_last5,team_points_last10,team_gd_last5,team_avg_goals_last5,team_avg_conceded_last5,team_win_rate_last10,h2h_points_last5,h2h_gd_last5,opp_points_last5,opp_points_last10,opp_gd_last5,opp_avg_goals_last5,opp_avg_conceded_last5,opp_win_rate_last10,points_last5_diff,gd_last5_diff,confederation_team_AFC,confederation_team_CAF,confederation_team_CONCACAF,confederation_team_CONMEBOL,confederation_team_OFC,confederation_team_UEFA,confederation_team_Unknown,confederation_opp_AFC,confederation_opp_CAF,confederation_opp_CONCACAF,confederation_opp_CONMEBOL,confederation_opp_OFC,confederation_opp_UEFA,confederation_opp_Unknown
23511,1,0,0,AFC Asian Cup qualification,Bangladesh,589.0,0.0,1340.174305,1381.026480,12486631.0,83929765.0,275.738115,200.769677,10.0,2551.703115,0.000000,25.639990,0,1,4.0,5.0,-5.0,0.6,1.6,0.1,0.0,0.0,0.0,1.0,-22.0,0.2,4.6,0.0,4.0,17.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
70545,1,0,1,AFC Challenge Cup qualification,Kyrgyzstan,192.0,0.0,1217.305507,1238.634298,28189672.0,148391139.0,364.663542,634.987070,127.0,1844.541334,0.000000,8.165958,0,1,5.0,5.0,-3.0,1.2,1.8,0.1,0.0,-1.0,1.0,2.0,-11.0,0.8,3.0,0.0,4.0,8.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
70896,1,0,1,SAFF Cup,Sri Lanka,2.0,0.0,1239.249260,1222.184346,28189672.0,148391139.0,364.663542,634.987070,14.5,3355.708894,2119.239639,27.673304,0,1,5.0,10.0,-3.0,0.8,1.4,0.2,1.0,-1.0,3.0,4.0,-6.0,0.6,1.8,0.0,2.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
70989,1,1,1,SAFF Cup,Sri Lanka,2.0,2.0,1239.249260,1115.375615,28189672.0,705516.0,364.663542,1828.154677,14.5,3355.708894,2473.933070,27.673304,0,0,6.0,11.0,0.0,1.2,1.2,0.2,0.0,0.0,2.0,6.0,-7.0,0.6,2.0,0.1,4.0,7.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
77767,1,0,1,AFC Challenge Cup qualification,India,95.0,0.0,1143.329449,1042.110790,28189672.0,705516.0,591.190030,2563.261224,205.5,1844.541334,1388.045688,24.293232,0,1,1.0,2.0,-20.0,0.4,4.4,0.0,0.0,-2.0,1.0,1.0,-29.0,0.4,6.2,0.0,0.0,9.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

,gender,is_home,neutral,tournament,venue_country,days_since_last_match_team,days_since_last_match_opp,elo_team,elo_opponent,population_team,population_opp,gdp_per_capita_team,gdp_per_capita_opp,altitude_venue,distance_travel_team,distance_travel_opp,temperature_venue,first_match_team,first_match_opp,team_points_last5,team_points_last10,team_gd_last5,team_avg_goals_last5,team_avg_conceded_last5,team_win_rate_last10,h2h_points_last5,h2h_gd_last5,opp_points_last5,opp_points_last10,opp_gd_last5,opp_avg_goals_last5,opp_avg_conceded_last5,opp_win_rate_last10,points_last5_diff,gd_last5_diff,confederation_team_AFC,confederation_team_CAF,confederation_team_CONCACAF,confederation_team_CONMEBOL,confederation_team_OFC,confederation_team_UEFA,confederation_team_Unknown,confederation_opp_AFC,confederation_opp_CAF,confederation_opp_CONCACAF,confederation_opp_CONMEBOL,confederation_opp_OFC,confederation_opp_UEFA,confederation_opp_Unknown
57925,1,0,0,Friendly,Niger,16.0,0.0,1568.462790,1443.910261,11239101.0,11622665.0,336.418739,228.235909,299.5,7336.303805,0.000000,19.930996,0,1,7.0,15.0,-1.0,1.8,2.0,0.4,10.0,3.0,4.0,11.0,-10.0,1.0,3.0,0.3,3.0,9.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
10135,1,1,0,Friendly,Mali,47.0,36.0,1501.067934,1537.864937,6153587.0,55569264.0,48.279925,92.960466,-9999.0,0.000000,7402.607417,32.532173,0,0,3.0,3.0,0.0,3.0,3.0,0.5,0.0,0.0,8.0,16.0,7.0,2.8,1.4,0.4,-5.0,-7.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
10297,1,0,0,Friendly,Nigeria,3.0,0.0,1534.877432,1511.044511,6153587.0,55569264.0,48.279925,92.960466,376.5,7402.607417,0.000000,26.371895,0,1,9.0,9.0,-2.0,2.2,2.6,0.6,3.0,1.0,5.0,15.0,-1.0,1.8,2.0,0.4,4.0,-1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
18228,1,1,0,Friendly,Mali,262.0,11.0,1539.079795,1640.461480,6153587.0,55569264.0,79.157411,209.226045,-9999.0,0.000000,7402.607417,24.874743,0,0,6.0,16.0,0.0,2.2,2.2,0.4,6.0,2.0,13.0,22.0,6.0,2.4,1.2,0.6,-7.0,-6.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
18283,1,0,0,Friendly,Nigeria,12.0,0.0,1547.133793,1649.661401,6153587.0,55569264.0,79.157411,209.226045,376.5,7402.607417,0.000000,25.731754,0,1,8.0,16.0,1.0,2.0,1.8,0.4,9.0,3.0,12.0,23.0,4.0,2.0,1.2,0.7,-4.0,-3.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [223]:
display(X_train.shape)
display(X_test.shape)

(63016, 49)

(15756, 49)

### venue_country & tournament

In [224]:
freq_cols = ['venue_country', 'tournament']

for col in freq_cols:
    freq_map = X_train[col].value_counts(normalize=True)
    X_train[col] = X_train[col].map(freq_map)
    X_test[col] = X_test[col].map(freq_map)
    X_test[col] = X_test[col].fillna(0)

In [225]:
display(X_train.shape)
display(X_test.shape)

(63016, 49)

(15756, 49)

In [226]:
display(X_train.info())
display(X_test.info())

<class 'pandas.core.frame.DataFrame'>
Index: 63016 entries, 23511 to 78468
Data columns (total 49 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       63016 non-null  category
 1   is_home                      63016 non-null  int64
 2   neutral                      63016 non-null  int64
 3   tournament                   63016 non-null  float64
 4   venue_country                63016 non-null  float64
 5   days_since_last_match_team   63016 non-null  float64
 6   days_since_last_match_opp    63016 non-null  float64
 7   elo_team                     63016 non-null  float64
 8   elo_opponent                 63016 non-null  float64
 9   population_team              63016 non-null  float64
 10  population_opp               63016 non-null  float64
 11  gdp_per_capita_team          63016 non-null  float64
 12  gdp_per_capita_opp           63016 non-null  float64
 13  altitude_venue               63016 non-null  float64
 14  distance_travel_team         63016 non-null  float64
 15  distance_travel_opp          63016 non-null  float64
 16  temperature_venue            63016 non-null  float64
 17  first_match_team             63016 non-null  int64
 18  first_match_opp              63016 non-null  int64
 19  team_points_last5            63016 non-null  float64
 20  team_points_last10           63016 non-null  float64
 21  team_gd_last5                63016 non-null  float64
 22  team_avg_goals_last5         63016 non-null  float64
 23  team_avg_conceded_last5      63016 non-null  float64
 24  team_win_rate_last10         63016 non-null  float64
 25  h2h_points_last5             63016 non-null  float64
 26  h2h_gd_last5                 63016 non-null  float64
 27  opp_points_last5             63016 non-null  float64
 28  opp_points_last10            63016 non-null  float64
 29  opp_gd_last5                 63016 non-null  float64
 30  opp_avg_goals_last5          63016 non-null  float64
 31  opp_avg_conceded_last5       63016 non-null  float64
 32  opp_win_rate_last10          63016 non-null  float64
 33  points_last5_diff            63016 non-null  float64
 34  gd_last5_diff                63016 non-null  float64
 35  confederation_team_AFC       63016 non-null  float64
 36  confederation_team_CAF       63016 non-null  float64
 37  confederation_team_CONCACAF  63016 non-null  float64
 38  confederation_team_CONMEBOL  63016 non-null  float64
 39  confederation_team_OFC       63016 non-null  float64
 40  confederation_team_UEFA      63016 non-null  float64
 41  confederation_team_Unknown   63016 non-null  float64
 42  confederation_opp_AFC        63016 non-null  float64
 43  confederation_opp_CAF        63016 non-null  float64
 44  confederation_opp_CONCACAF   63016 non-null  float64
 45  confederation_opp_CONMEBOL   63016 non-null  float64
 46  confederation_opp_OFC        63016 non-null  float64
 47  confederation_opp_UEFA       63016 non-null  float64
 48  confederation_opp_Unknown    63016 non-null  float64
dtypes: category(1), float64(44), int64(4)
memory usage: 23.6 MB

None

<class 'pandas.core.frame.DataFrame'>
Index: 15756 entries, 57925 to 68379
Data columns (total 49 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       15756 non-null  category
 1   is_home                      15756 non-null  int64
 2   neutral                      15756 non-null  int64
 3   tournament                   15756 non-null  float64
 4   venue_country                15756 non-null  float64
 5   days_since_last_match_team   15756 non-null  float64
 6   days_since_last_match_opp    15756 non-null  float64
 7   elo_team                     15756 non-null  float64
 8   elo_opponent                 15756 non-null  float64
 9   population_team              15756 non-null  float64
 10  population_opp               15756 non-null  float64
 11  gdp_per_capita_team          15756 non-null  float64
 12  gdp_per_capita_opp           15756 non-null  float64
 13  altitude_venue               15756 non-null  float64
 14  distance_travel_team         15756 non-null  float64
 15  distance_travel_opp          15756 non-null  float64
 16  temperature_venue            15756 non-null  float64
 17  first_match_team             15756 non-null  int64
 18  first_match_opp              15756 non-null  int64
 19  team_points_last5            15756 non-null  float64
 20  team_points_last10           15756 non-null  float64
 21  team_gd_last5                15756 non-null  float64
 22  team_avg_goals_last5         15756 non-null  float64
 23  team_avg_conceded_last5      15756 non-null  float64
 24  team_win_rate_last10         15756 non-null  float64
 25  h2h_points_last5             15756 non-null  float64
 26  h2h_gd_last5                 15756 non-null  float64
 27  opp_points_last5             15756 non-null  float64
 28  opp_points_last10            15756 non-null  float64
 29  opp_gd_last5                 15756 non-null  float64
 30  opp_avg_goals_last5          15756 non-null  float64
 31  opp_avg_conceded_last5       15756 non-null  float64
 32  opp_win_rate_last10          15756 non-null  float64
 33  points_last5_diff            15756 non-null  float64
 34  gd_last5_diff                15756 non-null  float64
 35  confederation_team_AFC       15756 non-null  float64
 36  confederation_team_CAF       15756 non-null  float64
 37  confederation_team_CONCACAF  15756 non-null  float64
 38  confederation_team_CONMEBOL  15756 non-null  float64
 39  confederation_team_OFC       15756 non-null  float64
 40  confederation_team_UEFA      15756 non-null  float64
 41  confederation_team_Unknown   15756 non-null  float64
 42  confederation_opp_AFC        15756 non-null  float64
 43  confederation_opp_CAF        15756 non-null  float64
 44  confederation_opp_CONCACAF   15756 non-null  float64
 45  confederation_opp_CONMEBOL   15756 non-null  float64
 46  confederation_opp_OFC        15756 non-null  float64
 47  confederation_opp_UEFA       15756 non-null  float64
 48  confederation_opp_Unknown    15756 non-null  float64
dtypes: category(1), float64(44), int64(4)
memory usage: 5.9 MB

None

In [227]:
display(X_train.isna().sum())
display(X_test.isna().sum())

gender                         0
is_home                        0
neutral                        0
tournament                     0
venue_country                  0
days_since_last_match_team     0
days_since_last_match_opp      0
elo_team                       0
elo_opponent                   0
population_team                0
population_opp                 0
gdp_per_capita_team            0
gdp_per_capita_opp             0
altitude_venue                 0
distance_travel_team           0
distance_travel_opp            0
temperature_venue              0
first_match_team               0
first_match_opp                0
team_points_last5              0
team_points_last10             0
team_gd_last5                  0
team_avg_goals_last5           0
team_avg_conceded_last5        0
team_win_rate_last10           0
h2h_points_last5               0
h2h_gd_last5                   0
opp_points_last5               0
opp_points_last10              0
opp_gd_last5                   0
opp_avg_goals_last5            0
opp_avg_conceded_last5         0
opp_win_rate_last10            0
points_last5_diff              0
gd_last5_diff                  0
confederation_team_AFC         0
confederation_team_CAF         0
confederation_team_CONCACAF    0
confederation_team_CONMEBOL    0
confederation_team_OFC         0
confederation_team_UEFA        0
confederation_team_Unknown     0
confederation_opp_AFC          0
confederation_opp_CAF          0
confederation_opp_CONCACAF     0
confederation_opp_CONMEBOL     0
confederation_opp_OFC          0
confederation_opp_UEFA         0
confederation_opp_Unknown      0
dtype: int64

gender                         0
is_home                        0
neutral                        0
tournament                     0
venue_country                  0
days_since_last_match_team     0
days_since_last_match_opp      0
elo_team                       0
elo_opponent                   0
population_team                0
population_opp                 0
gdp_per_capita_team            0
gdp_per_capita_opp             0
altitude_venue                 0
distance_travel_team           0
distance_travel_opp            0
temperature_venue              0
first_match_team               0
first_match_opp                0
team_points_last5              0
team_points_last10             0
team_gd_last5                  0
team_avg_goals_last5           0
team_avg_conceded_last5        0
team_win_rate_last10           0
h2h_points_last5               0
h2h_gd_last5                   0
opp_points_last5               0
opp_points_last10              0
opp_gd_last5                   0
opp_avg_goals_last5            0
opp_avg_conceded_last5         0
opp_win_rate_last10            0
points_last5_diff              0
gd_last5_diff                  0
confederation_team_AFC         0
confederation_team_CAF         0
confederation_team_CONCACAF    0
confederation_team_CONMEBOL    0
confederation_team_OFC         0
confederation_team_UEFA        0
confederation_team_Unknown     0
confederation_opp_AFC          0
confederation_opp_CAF          0
confederation_opp_CONCACAF     0
confederation_opp_CONMEBOL     0
confederation_opp_OFC          0
confederation_opp_UEFA         0
confederation_opp_Unknown      0
dtype: int64

# MODELING

In [228]:
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor

In [229]:
rf = RandomForestRegressor(random_state=42)
xgb = XGBRegressor(random_state=42)
lgbm = LGBMRegressor(random_state=42)
gb = GradientBoostingRegressor(random_state=42)
ab = AdaBoostRegressor(random_state=42)

In [230]:
from sklearn.multioutput import RegressorChain

chain_rf = RegressorChain(base_estimator=rf, order=[0, 1])
chain_xgb = RegressorChain(base_estimator=xgb, order=[0, 1])
chain_lgbm = RegressorChain(base_estimator=lgbm, order=[0, 1])
chain_gb = RegressorChain(base_estimator=gb, order=[0, 1])
chain_ab = RegressorChain(base_estimator=ab, order=[0, 1])

In [231]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

models = {
    'Random Forest': chain_rf,
    'XGBoost': chain_xgb,
    'LightGBM': chain_lgbm,
    'Gradient Boosting': chain_gb,
    'Ada Boost': chain_ab
}

In [232]:
from sklearn.model_selection import KFold, cross_validate

kf = KFold(n_splits=3, shuffle=True, random_state=42)

result = []

for name, model in models.items():
    cv_scores = cross_validate(model,
                               X_train, y_train,
                               cv=kf,
                               scoring=['neg_root_mean_squared_error', 'neg_mean_absolute_error', 'r2'],
                               n_jobs=-1)
    result.append({
        'Model': name,
        'RMSE': -cv_scores['test_neg_root_mean_squared_error'].mean(),
        'MAE': -cv_scores['test_neg_mean_absolute_error'].mean(),
        'R2': cv_scores['test_r2'].mean()
    })

df_results = pd.DataFrame(result).sort_values(by='R2', ascending=False).reset_index(drop=True)

df_results

               Model      RMSE       MAE        R2
0           LightGBM  1.470791  1.041563  0.322753
1      Random Forest  1.501563  1.068590  0.294066
2            XGBoost  1.503857  1.062531  0.291854
3  Gradient Boosting  1.505923  1.058670  0.289988
4          Ada Boost  2.224118  1.870810 -0.583888

In [233]:
from sklearn.metrics import root_mean_squared_error, mean_absolute_error, r2_score

result_2 = []

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    y_pred_round = np.round(y_pred).astype(int)

    rmse = root_mean_squared_error(y_test, y_pred_round)
    mae = mean_absolute_error(y_test, y_pred_round)
    r2 = r2_score(y_test, y_pred_round)

    result_2.append({
        'Model': name,
        'RMSE': rmse,
        'MAE': mae,
        'R2': r2
    })

df_results_2 = pd.DataFrame(result_2).sort_values('R2', ascending=False).reset_index(drop=True)
df_results_2

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002764 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4181
[LightGBM] [Info] Number of data points in the train set: 63016, number of used features: 49
[LightGBM] [Info] Start training from score 1.560715
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002609 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4205
[LightGBM] [Info] Number of data points in the train set: 63016, number of used features: 50
[LightGBM] [Info] Start training from score 1.560715

c:\Users\jojo0\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\jojo0\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\jojo0\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\jojo0\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

               Model      RMSE       MAE        R2
0           LightGBM  1.515653  1.028370  0.299384
1            XGBoost  1.539390  1.044681  0.277259
2      Random Forest  1.546956  1.062516  0.270136
3  Gradient Boosting  1.547923  1.042746  0.269235
4          Ada Boost  2.712072  2.342790 -1.323735